#Challenge 2
#
#Each new term in the Fibonacci sequence is generated by adding the previous two terms.
#By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89
#
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even valued terms.

#Potential method:
#Create vector of all numbers in the Fibonacci sequence < 4mil
#Look through vector and check if each element is divisible by 2, return true or false (use lapply/sapply)
#Select indices of vector where true
#Sum them for the answer

### METHOD 1 ###
#1. Create vector of the Fibonacci sequence
f <- NULL
i <-  1
x <- 1
while(x < 4000000){
  
  f[i] <- x
  
  if(x == 1){x <- 2} 
  
  else {x <- (f[i] + f[i-1])}
  
  i <- i + 1
}

#2. Create function to check if the result of dividing by 2 is an integer, return TRUE / FALSE
check <- function(x){
  if((x/2)%%1==0){res = TRUE}
  
  else {res = FALSE}
  
  return(res)
}

#3. Apply the function to each element of vector
test <- lapply(f,check)

#4. Record indices where test is TRUE
inds <- which(test == TRUE)

f[inds]

#5. Sum the values of those elements
sum(f[inds])

#Answer is 4,613,732
