# Challenge 2
# Each term in the Finbonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1,2,3,4,5,13,21,34,55,89...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even valued terms.

# Use a while loop to add the even Fibonacci terms
$i = 1

$j = 0

while($i -lt 4000000){

    if($i % 2 -eq 0){$Fib += $i}

    $i = $i + $j

    $j = $i - $j
}

# Check result
$Fib

# Result is 4,613,732
